[book]
authors = ["Philip Linden"]
language = "en"
multilingual = false
title = "spacetime documentation"
src = "docs"

[build]
build-dir = "docs/book"
create-missing = false

[output.html]
mathjax-support = true
smart-punctuation = true
# no-section-label = true
git-repository-url = "https://github.com/philiplinden/spacetime"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/philiplinden/spacetime/edit/main/docs/{path}"

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.fold]
enable = true     # whether or not to enable section folding
level = 1         # the depth to start folding
