[package]
name = "clocss-abm"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
readme = "README.md"
description = "an Agent-Based Model of Heterogeneous Lunar Networks"
authors = ["Philip Linden <lindenphilipj@gmail.com>"]
homepage = "https://philiplinden.github.io/clocss-abm/"
repository = "https://github.com/philiplinden/clocss-abm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.0", features = ["dynamic_linking"] }
bevy-inspector-egui = { version = "0.22.1", features = ["highlight_changes"] }
bevy_egui = "0.24.0"
bevy_rapier3d = { version = "0.23.0", features = ["enhanced-determinism", "debug-render"] }
hifitime = "3.8.5"
particular = { version = "0.6.1", features = ["gpu"] }
rand = "0.8.5"
uuid = { version = "1.6.1", features = ["v4"] }

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
incremental = true

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
