site_name: spacetime
site_description: A real(istic) time simulator.
repo_url: https://github.com/philiplinden/spacetime
repo_name: philiplinden/spacetime

nav:
  - design:
    - goals: index.md
    - tools_and_frameworks: design/tools_and_frameworks.md
  - technical: technical/
  - devlog:
    - latest: devlog/v0.2.0.md
    - v0.1.0: devlog/v0.1.0.md
    - v0.0.0: devlog/v0.0.0.md
theme:
  name: material
  font:
    text: Lekton #Changa #Lekton #Quicksand #Assistant
    code: Source Code Pro
  icon:
    logo: fontawesome/solid/clock-rotate-left
  palette:
    - scheme: slate
      primary: black
      accent: green
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition  # adds a bunch of extra callout block styles
  - attr_list   # adds HTML attrs and CSS classes to markdown elements
  - def_list    # enables "definition lists" by using TERM\n:\tDEFINITION syntax
  - footnotes   # enables inline footnotes by using [^1] to mark and [^1]: to define
  - pymdownx.mark # enables markdown highlighting with `==text==` syntax
  - pymdownx.tilde # enables markdown strikethrough with `~~text~~` syntax
  - pymdownx.snippets # grabs snippets from files instead of copy/pasting (https://facelessuser.github.io/pymdown-extensions/extensions/snippets/)
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: '#'
      baselevel: '2'

plugins:
  - search
  - include_dir_to_nav
  - git-authors
  - offline

# Enable LaTeX-formatted math
extra_javascript:
  - extras/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - extras/site.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
