site_name: spacetime
site_description: A Simulation of Heterogeneous Networked Lunar Clocks.
repo_url: https://github.com/philiplinden/spacetime
repo_name: philiplinden/spacetime

nav:
  - spacetime:
    - home: index.md
    - approach: approach.md
    - design decisions: design-decisions.md
  - learning by example:
    - python demos: python-demos.md
    - ipy notebooks: notebooks/
  - technical topics: technical/
  - api docs:
    - spacetime_bridge: api/doc/spacetime_bridge/index.html
    - spacetime_core: api/doc/spacetime_core/index.html
theme:
  name: material
  font:
    text: Space Mono
    code: Source Code Pro
  icon:
    logo: fontawesome/solid/clock-rotate-left
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: '#'
      baselevel: '2'

plugins:
  - search
  - include_dir_to_nav
  - git-authors
  - offline

# Enable LaTeX-formatted math
extra_javascript:
  - scripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
