site_name: spacetime
site_description: A Simulation of Heterogeneous Networked Lunar Clocks.
repo_url: https://github.com/philiplinden/spacetime
repo_name: philiplinden/spacetime

nav:
  - spacetime:
    - Home: index.md
    - Approach: approach.md
    - Design Decisions: design-decisions.md
  - Learning:
    - Python Demos: python-demos.md
    - iPy Notebooks: notebooks/
  - Project:
    - Agents: agents.md
  - API Documentation: api/doc/spacetime/index.html
theme:
  name: material
  font:
    text: Space Mono
    code: Source Code Pro
  icon:
    logo: fontawesome/solid/clock-rotate-left
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search
    - search.suggest
    - search.highlight

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: '#'
      baselevel: '2'

plugins:
  - search
  - include_dir_to_nav
  - git-authors
  - offline
