[package]
name = "lofitime"
description = "Handy translations between Hifitime and Chrono datetimes and durations."
version = "0.2.0"
authors.workspace = true
edition.workspace = true

[dependencies]
chrono = "0.4.38"
hifitime = { workspace = true }
