name: Docs
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write  # To push a branch
  pages: write  # To push to a GitHub Pages site
  id-token: write # To update the deployment status

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Populate target directory from cache
        uses: Leafwing-Studios/cargo-cache@v2

      - name: Install mdbook and admonish plugin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: |
            mdbook
            mdbook-admonish
            mdbook-katex
            mdbook-mermaid

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Book
        run: |
          mdbook-admonish install ./docs
          mdbook-mermaid install ./docs
          mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './docs/book'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs/book
